# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ğŸ˜…
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  æ²¡æœ‰æè¿°ã€‚
# keyword: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sz2528.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: SZ2528

# Navigation links
nav:
  home: "/"
  tags: "/tags.html"

# Author é…ç½®åšä¸»ä¿¡æ¯
author: "SZ2528"
nickname: "å¥½ä¸œè¥¿å°±è¦æ¥äº†"
bio: "What's up"
avatar: "assets/img/profile.png"

# Search
search: true

# Night mode
nightMode: true

# SNS settings é…ç½®ç¤¾äº¤ç½‘ç«™url
sns:
  github: "//github.com/SZ2528"

# RSS
RSS: false

# Share
social-share: true # å¼€å¯æˆ–è€…å…³é—­åˆ†äº«åŠŸèƒ½
social-share-items: ["wechat", "weibo", "douban","twitter"]

# theme color
theme-color: "default" # pink or default

# Tags
recommend-tags: true
recommend-condition-size: 12

# Build settings
markdown: GFM
remote_theme: kaeyleo/jekyll-theme-H2O
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-feed
paginate: 6
paginate_path: "page:num"
exclude: ["node_modules", "dev", "package.json", "gulpfile.js", ".gitignore", "README.md"]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
